# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-13 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geotag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classifieds',
            fields=[
                ('classified_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=140)),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geotag.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=140)),
                ('name', models.CharField(max_length=30)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('max_group_size', models.IntegerField()),
                ('fee', models.FloatField()),
                ('public', models.BooleanField()),
                ('host_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geotag.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Is_Attending',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Is_Friend',
            fields=[
                ('user1_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user2_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('popularity', models.FloatField()),
                ('coord_x', models.FloatField()),
                ('coord_y', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geotag.Locations'),
        ),
    ]
